ALTER TABLE crud_click_bus
DROP COLUMN updated_at, 
DROP COLUMN created_at, 
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;